### ISSUE TITLE
FatalErrorException in GuzzleHttpAdapter.php line 135:

### ISSUE THREAD

**Issue by aggrogg** [GrahamCampbell/Laravel-DigitalOcean#13]
Got this installed and setup - updated my digitalocean.php config file with my tokens. 

Running any command e.g. 
DigitalOcean::connection('main')->region()->getAll();

Results in: 
FatalErrorException in GuzzleHttpAdapter.php line 135:
Call to a member function getBody() on null

I am using guzzlehttp. 

Token is correct if I run a DO API call manually via command line. I am running the site locally on XAMPP (no SSL)

**Comment by GrahamCampbell** [comment]
The is an issue with the other repo. We can discuss on your other report.
