### ISSUE TITLE
Getting a single Droplet?

### ISSUE THREAD

**Issue by mikkelbfriis** [GrahamCampbell/Laravel-DigitalOcean#16]
Isn't there a method for getting just a single droplet for the specific ID?
Like:

```
    public function power($droplet_id) {

        dd(DigitalOcean::droplet($droplet_id));
        return redirect()->back();
    }
```

**Comment by GrahamCampbell** [comment]
Yes `DigitalOcean::droplet()->getById($droplet_id)` will return a droplet entity.

See https://github.com/toin0u/DigitalOceanV2/blob/master/src/Api/Droplet.php#L102 and https://github.com/toin0u/DigitalOceanV2/blob/master/src/Entity/Droplet.php.

**Comment by mikkelbfriis** [comment]
Thanks! Way better than

```
private function droplet($id) {
    foreach (DigitalOcean::droplet()->getAll() as $droplet) {
        if ($droplet->id == $id) {
            return $droplet;
        }
    }

    return null;
}
```
