### ISSUE TITLE
Installed

### ISSUE THREAD

**Issue by JBird608** [GrahamCampbell/Laravel-DigitalOcean#19]
Hey, 

I was hope you could give me some pointers on how to get this working? So far I have go this installed and added a token. How do I say list the droplets on my account or see if its even corrected to my the API successfully?

Cheers.

**Comment by danieluyo** [comment]
Real Examples
Here you can see an example of just how simple this package is to use. Out of the box, the default adapter is main. After you enter your authentication details in the config file, it will just work:

```php
<?php
use GrahamCampbell\DigitalOcean\Facades\DigitalOcean;

$data = DigitalOcean::region()->getAll();

dd($data);
```

**Comment by tarecord** [comment]
Could this be used to access Digital Ocean on behalf of other users after OAuth authentication? I'm having a hard time finding a way to insert the access key when accessing the class.

**Comment by krisnaw** [comment]
Yes, you can @tarecord. 
` $do = $this->doFactory->make(['driver' => 'guzzlehttp', 'token' => 'asdf']);`

**Comment by LukaSikic** [comment]
@krisnaw could you explain your answer? $do is GuzzleHttpAdapter. How do we call region() with $do?

**Comment by krisnaw** [comment]
@LukaSikic 
$do is the instance, you can call the function as usual.
`  $do->region();`
