### ISSUE TITLE
Add option for UserData on droplet()->create

### ISSUE THREAD

**Issue by railto** [GrahamCampbell/Laravel-DigitalOcean#2]
It would be great if you (or someone else more knowledgable than myself) could add in the ability to pass UserData on new droplet creation.

This would likely need some conditional checking before running the call as UserData is only available on selected OSs in certain locations.  More at https://developers.digitalocean.com/#create-a-new-droplet

**Comment by GrahamCampbell** [comment]
Ok, this is now supported. Just released 0.4.0. :)
