### ISSUE TITLE
Laravel 5.7 Call to a member function getBody() on null

### ISSUE THREAD

**Issue by AndreFabris** [GrahamCampbell/Laravel-DigitalOcean#25]
"graham-campbell/digitalocean": "^5.1",
        "guzzlehttp/guzzle": "^6.3",
        "kriswallsmith/buzz": "^0.17.2"

when calling any function for example DigitalOcean::size()->getAll();

Issue with C:\xampp\htdocs\front\myadmin\vendor\toin0u\digitalocean-v2\src\Adapter\GuzzleHttpAdapter.php

Line 132:  $body = (string) $this->response->getBody();

Any ideas

**Comment by GrahamCampbell** [comment]
Not sure. I think there is an issue tracking this on the upstream repo. If not, please create one.

**Comment by AndreFabris** [comment]
We did, however, I updated my composer files since I created this ticket, there was your update there too, and that has solved the issue
