### ISSUE TITLE
phpstorm does not recognize facade, even with ide-helper

### ISSUE THREAD

**Issue by michabbb** [GrahamCampbell/Laravel-DigitalOcean#26]
hi there. i installed the ide-helper and tried stuff like that:

https://stackoverflow.com/a/51849199/1092858

but i am not able to make phpstorm recognize commands like this:

`DigitalOcean::droplet()->getAll()`

"droplet" and all other commands are unknown.
any idea ?

thanks!

**Comment by michabbb** [comment]
rename subject

**Comment by GrahamCampbell** [comment]
I'm not sure. Maybe try taking this up with the IDE helper package?

**Comment by michabbb** [comment]
Pardon, what do you mean with "try taking up" and what exactly is the "ide helper package" for you? Thanks

**Comment by GrahamCampbell** [comment]
> i installed the ide-helper

You said you'd tried the IDE helper package. Please report to them that it is not picking up the methods from the facades in this package.

**Comment by CraigHarley** [comment]
@michabbb you can work around this by doing:

```
/** @var \DigitalOceanV2\DigitalOceanV2 $do */
$do = DigitalOcean::connection('main');
```

Now the intellisense on `$do` will work.

**Comment by michabbb** [comment]
@CraigHarley thanks for your try to help, but your code has nothing to do with "recognizing facades", only with "recognizing what's behind a variable" 😏

**Comment by CraigHarley** [comment]
Cool well feel free to create a PR to add the type hinting like this:

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Facades/DB.php#L6

**Comment by michabbb** [comment]
@CraigHarley so what do you think is this: https://github.com/GrahamCampbell/Laravel-DigitalOcean/blob/master/src/Facades/DigitalOcean.php ???

**Comment by CraigHarley** [comment]
There's no type hinting on that link.

An example is the line I linked to.

**Comment by CraigHarley** [comment]
Like this:
`@method static \Illuminate\Database\ConnectionInterface connection(string $name = null)`
