### ISSUE TITLE
TTL not set while creating domain record

### ISSUE THREAD

**Issue by aadags** [GrahamCampbell/Laravel-DigitalOcean#28]
Hi Graham
I have been trying set TTL on the domain record create and update methods but no luck.

The toin0u library did not state it either
// return the DomainRecord entity 123 of the domain 'baz.dk' updated with new-name, new-data, priority 1, port 2, weight 3, flags 0, tag issue (name, data, priority, port, weight, flags and tag are nullable)
$updated = $domainRecord->update('baz.dk', 123, 'new-name', 'new-data', 1, 2, 3, 0, 'issue');

kindly assist

**Comment by GrahamCampbell** [comment]
I'm not sure, sorry. Maybe check DigitalOcean's raw API docs, and look at the library code to see how their docs translate to the PHP code calls?

**Comment by GrahamCampbell** [comment]
Also, if you are spending more than (I think $500/month) on DigitalOcean, you should have access to their premium support, so you can reach out to them for help.

**Comment by aadags** [comment]
ok thanks
