### ISSUE TITLE
Issues running publish:config

### ISSUE THREAD

**Issue by widey** [GrahamCampbell/Laravel-DigitalOcean#3]
when I try and run (using Laravel 5)

php artisan publish:config graham-campbell/digitalocean

I get an error:

exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /home/vagrant/code/l5try/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:140
Stack trace:

I'm just trying to confirm if this is something I did wrong or if it's because L5 is still in flux.

Thanks

**Comment by widey** [comment]
Hi Graham,

I see that package config has been removed from L5, do you know if there's a way to work around this in the mean time?

Thanks

**Comment by GrahamCampbell** [comment]
Only versions of Laravel 5 before the package method was removed are currently supported. I'll be upgrading this package within a few weeks.

You can add my fork of laravel to the "repositories" section of your composer file like I do in this repo to get the tests to run. It's essentially locked at the last version of laravel 5 to support the old package system.
