### ISSUE TITLE
Unable to configure

### ISSUE THREAD

**Issue by radua** [GrahamCampbell/Laravel-DigitalOcean#30]
Hi,

I installed the package as per the instructions with guzzlehttp. I have put my DO token in config/digitalocean.php but no matter which connection I try to use, I always get Connection {connection_name} is not configured.
Please guide me as to where am I going wrong.
Thanks!

**Comment by GrahamCampbell** [comment]
Do you need to rebuild your config cache?

**Comment by radua** [comment]
@GrahamCampbell : Yes, config cache was the issue. Sorry! and Thanks again :)
