### ISSUE TITLE
How to create droplet using "snapshot id"?

### ISSUE THREAD

**Issue by StarMonk** [GrahamCampbell/Laravel-DigitalOcean#31]
I have created a snapshot of my droplet and I want to create a new droplet with the same snapshot, how do I do it?

Thanks

**Comment by GrahamCampbell** [comment]
`DigitalOcean::droplet()->create(...)`. Pass the snapshot ID as the 4th parameter: https://github.com/DigitalOceanPHP/Client/blob/2.3/src/Api/Droplet.php#L111-L131.

**Comment by GrahamCampbell** [comment]
Pass the snapshot ID as the 3rd parameter: https://github.com/DigitalOceanPHP/Client/blob/2.3/src/Api/Droplet.php#L111-L131.
