### ISSUE TITLE
Undefined class constant 'VERSION' 

### ISSUE THREAD

**Issue by emirgo** [GrahamCampbell/Laravel-DigitalOcean#33]
I am facing this issue:
![image](https://user-images.githubusercontent.com/40762681/85950705-ba301880-b95e-11ea-8666-5c9fe4d1a819.png)

**Comment by GrahamCampbell** [comment]
This happens because you installed Guzzle 7, but the package requires Guzzle 5 or 6.

**Comment by GrahamCampbell** [comment]
I've updated the example install comment to ask for Guzzle 6 on our readme. :)

**Comment by assemblu** [comment]
Thanks a bunch! Seems like I just missed it.
