### ISSUE TITLE
Dynamically set the API access token

### ISSUE THREAD

**Issue by 06chaynes** [GrahamCampbell/Laravel-DigitalOcean#6]
I have the bridge working beautifully with my static token setting as described in your setup documentation (using guzzle5). Everything works as expected but I would like to be able to set the token 'on the fly' if you will. 

Can you explain how I can override the token?

**Comment by GrahamCampbell** [comment]
It would be a bad practice to "override" the token, but, I do have another suggestion...

**Comment by GrahamCampbell** [comment]
Basically, just directly interact with the factory class: https://github.com/GrahamCampbell/Laravel-DigitalOcean/blob/master/src/DigitalOceanFactory.php.

You can resolve it out of the IOC, or, you can also get it by calling the `getFactory` method on the manager class (through the facade we have if you like facades).

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/blob/master/app/GitHub/ClientFactory.php

That example is somewhat similar, but is for my github package rather than this one. The principle is the same though. :)

**Comment by 06chaynes** [comment]
I am looking through but I unfortunately don't think I am fully grasping what needs to be done. 

 The overall goal of what I am trying to accomplish is to allow our users to enter their own token to manage their accounts. I can't enter each one as a static connection so I will need to be able to pull the key from the database and not a static config file. 

Can you maybe elaborate a bit on your example?

Also this really is a great package that has already saved me a ton of dev time so thank you sir, it is much appreciated.

**Comment by GrahamCampbell** [comment]
You just need to call the make method on the factory object with the user's details, then play with the object that comes out.

**Comment by royduin** [comment]
Example:
```
$info = DigitalOcean::getFactory()->make([
    'token' => $value,
    'driver' => 'guzzle',
])->account()->getUserInformation();
```
